### ISSUE TITLE
cannot install sentiment; Rstem not available

### ISSUE THREAD

**Issue by egonw** [neilfws/Twitter#1]
> install.packages(pkgs=c("sentiment"))
> Installing package(s) into ‘/home/egonw/R/i486-pc-linux-gnu-library/2.15’
> (as ‘lib’ is unspecified)
> Warning: dependency ‘Rstem’ is not available
> trying URL 'http://cran.xl-mirror.nl/src/contrib/sentiment_0.2.tar.gz'
> Content type 'application/x-gzip' length 38880 bytes (37 Kb)
> # opened URL
> 
> downloaded 37 Kb

ERROR: dependency ‘Rstem’ is not available for package ‘sentiment’
- removing ‘/home/egonw/R/i486-pc-linux-gnu-library/2.15/sentiment’

The downloaded source packages are in
        ‘/tmp/Rtmp47qYCF/downloaded_packages’
Warning message:
In install.packages(pkgs = c("sentiment")) :
  installation of package ‘sentiment’ had non-zero exit status

**Comment by Anmol-Paktor** [comment]
This is not working anymore

**Comment by neilfws** [comment]
It's not clear from the previous comment what is "not working". 

Both Rstem and sentiment were removed from CRAN, but both can still be downloaded and installed. You also need to install the tm package. I just did this successfully on OS X with R 3.3.
