### ISSUE TITLE
user2018 - tweets-top-sources chunk

### ISSUE THREAD

**Issue by chalg** [neilfws/Twitter#2]
Hi - I don't think you need:
`distinct(screen_name, source) %>%`
under Sources. screen_name is not relevant for overall count of source and is distorting the overall count. The overall counts are much higher.
Example:
Twitter for Android | 1933
Twitter for iPhone | 1912
Twitter Web Client | 1172

**Comment by neilfws** [comment]
Screen name is relevant, since we're not interested in counting the same source multiple times from the same user. We want to know clients per user, not clients per tweet.
